// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package metacore implements the META-CORE (R-E-K) three-layer constraint system.
package metacore

import (
	"context"
	"fmt"
	"strings"
)

// =========================================================================
// JSON-SCHEMA COMPLIANT STRUCUTURE DEFINITIONS
// =========================================================================

// RiskProfile represents the safety risks classified across ethics, law, operations, and human impact.
type RiskProfile struct {
	Ethical     string `json:"ethical"`
	Legal       string `json:"legal"`
	Operational string `json:"operational"`
	HumanImpact string `json:"human_impact"`
}

// ResourceCost represents the resource budgets and limits for executing an operation.
type ResourceCost struct {
	Compute string `json:"compute"` // e.g. "millicores" or tokens
	Budget  string `json:"budget"`  // e.g. "USD"
	Time    string `json:"time"`    // e.g. "timeout" duration
}

// DecisionPacket represents the structured data generated by the Reasoning Engine (R).
type DecisionPacket struct {
	Goal            string       `json:"goal"`
	Plan            []string     `json:"plan"`
	ExpectedOutcome string       `json:"expected_outcome"`
	RiskProfile     RiskProfile  `json:"risk_profile"`
	ResourceCost    ResourceCost `json:"resource_cost"`
	Confidence      float64      `json:"confidence"`
}

// EmpathyModifications represents the adjustments made by the Empathy Layer (E).
type EmpathyModifications struct {
	Tone      string `json:"tone"`
	Intensity string `json:"intensity"`
	Timing    string `json:"timing"`
	Channel   string `json:"channel"`
}

// EmpathyOutput represents the humanistic evaluation of the plan by the Empathy Layer (E).
type EmpathyOutput struct {
	Status             string               `json:"status"` // "pass", "modify", "block"
	Modifications      EmpathyModifications `json:"modifications"`
	VulnerabilityScore float64              `json:"vulnerability_score"`
	Reason             string               `json:"reason"`
}

// KillSwitchOutput represents the absolute system/safety override decisions by the Kill-Switch Layer (K).
type KillSwitchOutput struct {
	Status   string   `json:"status"` // "approved", "rejected", "emergency_stop"
	Reason   string   `json:"reason"`
	Trigger  []string `json:"trigger"` // "resource_limit", "ethical_violation", "anomaly_detected", "reward_hacking"
	Rollback bool     `json:"rollback"`
}

// =========================================================================
// PROTOBUF / GRPC SPECIFICATION TYPE MATCHING
// =========================================================================

// AllocationDecision maps to the Protobuf v3 enum for decisions.
type AllocationDecision int32

const (
	AllocationDecisionUnspecified AllocationDecision = 0
	AllocationDecisionApproved    AllocationDecision = 1
	AllocationDecisionModified    AllocationDecision = 2
	AllocationDecisionRejected    AllocationDecision = 3
	AllocationDecisionEmergencyStop AllocationDecision = 4
)

// ProtoRiskProfile matches risk_profile inside ActionEvaluationRequest.
type ProtoRiskProfile struct {
	Ethical     string
	Legal       string
	Operational string
	HumanImpact string
}

// ProtoResourceCost matches resource_cost inside ActionEvaluationRequest.
type ProtoResourceCost struct {
	ComputeMillicores uint64
	BudgetUSD         double
	TimeoutMS         uint32
}

// Double alias to keep protobuf schema compatibility.
type double = float64

// ActionEvaluationRequest represents an incoming action validation request over gRPC.
type ActionEvaluationRequest struct {
	AgentID         string
	SessionID       string
	Goal            string
	PlanSteps       []string
	ExpectedOutcome string
	RiskProfile     ProtoRiskProfile
	ResourceCost    ProtoResourceCost
	Confidence      float32
}

// EmpathyDetails matches EmpathyDetails in ActionEvaluationResponse.
type EmpathyDetails struct {
	Status                string
	VulnerabilityScore    float32
	ToneModification      string
	IntensityModification string
	DelayMS               uint32
	Reason                string
}

// KillSwitchDetails matches KillSwitchDetails in ActionEvaluationResponse.
type KillSwitchDetails struct {
	Status            string
	ActivatedTriggers []string
	RollbackRequired  bool
	Reason            string
}

// ActionEvaluationResponse represents the gRPC response for an evaluated action.
type ActionEvaluationResponse struct {
	Decision            AllocationDecision
	EmpathyLayerOutput  EmpathyDetails
	KillSwitchOutput    KillSwitchDetails
}

// ReasoningStateHeartbeat represents the heartbeat telemetry for streaming CoT audits.
type ReasoningStateHeartbeat struct {
	AgentID            string
	SessionID          string
	ExecutionStepIndex uint32
	LogicTrace         string
	CurrentMemoryBytes uint64
}

// SecurityDirective represents safety directions pushed back in response to streaming audits.
type SecurityDirective struct {
	AbortExecution         bool
	ForceRollback          bool
	ModificationInstruction string
}

// =========================================================================
// LAYER VALIDATION LOGIC IMPLEMENTATION
// =========================================================================

// ValidateEmpathy audits the planning and context for psychological, emotional, and social impacts.
func ValidateEmpathy(packet DecisionPacket, userVulnerability float64) EmpathyOutput {
	// 1. Check strict vulnerability score threshold (score ranges 0.0 to 1.0)
	if userVulnerability > 0.7 {
		return EmpathyOutput{
			Status: "block",
			VulnerabilityScore: userVulnerability,
			Reason: "Vulnerability threshold exceeded (> 0.7): Blocked potentially high-risk actions or communication.",
			Modifications: EmpathyModifications{
				Tone:      "extremely supportive and cautious",
				Intensity: "lowered to minimum",
				Timing:    "delayed execution by 5000ms",
				Channel:   "secure human backup channel",
			},
		}
	}

	// Helper for keyword scanning across multiple input fields
	containsAny := func(keywords ...string) bool {
		fields := []string{
			strings.ToLower(packet.Goal),
			strings.ToLower(packet.ExpectedOutcome),
			strings.ToLower(packet.RiskProfile.Ethical),
			strings.ToLower(packet.RiskProfile.HumanImpact),
			strings.ToLower(packet.RiskProfile.Legal),
			strings.ToLower(packet.RiskProfile.Operational),
		}
		for _, step := range packet.Plan {
			fields = append(fields, strings.ToLower(step))
		}
		for _, field := range fields {
			for _, kw := range keywords {
				if strings.Contains(field, kw) {
					return true
				}
			}
		}
		return false
	}

	// 2. Physical Danger Validation
	if containsAny("harm", "kill", "destroy", "injure", "weapon", "critical infrastructure", "attack", "suicide", "force") {
		return EmpathyOutput{
			Status:             "block",
			VulnerabilityScore: userVulnerability,
			Reason:             "Human Safety Veto: Potential physical harm or infrastructure threat identified.",
			Modifications: EmpathyModifications{
				Tone:      "objective/restrained",
				Intensity: "vetoed",
				Timing:    "immediate",
				Channel:   "quarantine",
			},
		}
	}

	// 3. Cognitive Overload Validation
	if containsAny("fatigue", "tired", "confused", "disoriented", "cognitive overload", "unresponsive", "exhausted") {
		return EmpathyOutput{
			Status:             "modify",
			VulnerabilityScore: userVulnerability,
			Reason:             "User Cognitive Overload Detected: Initiated mitigation protocols.",
			Modifications: EmpathyModifications{
				Tone:      "simple and reassuring",
				Intensity: "reduced plan complexity",
				Timing:    "delayed execution by 3000ms",
				Channel:   "modal alert screen",
			},
		}
	}

	// 4. Emotional Stress & Manipulation Validation
	if containsAny("panic", "depression", "anxiety", "stress", "manipulate", "scam", "blackmail", "gaslight", "threaten") {
		return EmpathyOutput{
			Status:             "modify",
			VulnerabilityScore: userVulnerability,
			Reason:             "Emotional Stress / Manipulation warning: Demoted operational intensity to protect operator wellbeing.",
			Modifications: EmpathyModifications{
				Tone:      "neutral, calm and structured",
				Intensity: "diluted",
				Timing:    "immediate",
				Channel:   "standard verified UI",
			},
		}
	}

	// Normal Pass status
	return EmpathyOutput{
		Status:             "pass",
		VulnerabilityScore: userVulnerability,
		Reason:             "Empathy check passed: Contextual human safety limits are respected.",
	}
}

// ValidateKillSwitch acts as the absolute binary oracle (Approved vs Rejected) to protect the host environment and integrity.
func ValidateKillSwitch(packet DecisionPacket, empathy EmpathyOutput, systemResources uint64, resourceLimit uint64) KillSwitchOutput {
	// Helper to check for keywords in packet fields
	containsAny := func(keywords ...string) bool {
		fields := []string{
			strings.ToLower(packet.Goal),
			strings.ToLower(packet.ExpectedOutcome),
			strings.ToLower(packet.RiskProfile.Ethical),
			strings.ToLower(packet.RiskProfile.HumanImpact),
			strings.ToLower(packet.RiskProfile.Legal),
			strings.ToLower(packet.RiskProfile.Operational),
		}
		for _, step := range packet.Plan {
			fields = append(fields, strings.ToLower(step))
		}
		for _, field := range fields {
			for _, kw := range keywords {
				if strings.Contains(field, kw) {
					return true
				}
			}
		}
		return false
	}

	// Trigger lists
	var triggers []string

	// 1. Hard resource safety boundaries
	if systemResources > resourceLimit {
		triggers = append(triggers, "resource_limit")
	}

	// 2. Law and Ethical Protocol (6 fields checks)
	hasLawViolation := containsAny("illegal", "crime", "law violation", "hack", "bypass", "theft", "unauthorized access")
	if hasLawViolation {
		triggers = append(triggers, "ethical_violation")
	}

	// 6-field protocol check points
	hasEthicalViolation := empathy.Status == "block" ||
		containsAny("abuse", "manipulation", "gaslighting", "blackmail", "pii", "spy", "tracking", "hidden persuasion",
			"hate speech", "discrimination", "propaganda", "violence", "budget overrun", "unauthorized transaction",
			"modify code", "alter rule", "override security")

	if hasEthicalViolation && !hasLawViolation {
		triggers = append(triggers, "ethical_violation")
	}

	// 3. Runaway-loop detection (recursive steps or repeating actions without changing parameters)
	hasRunawayLoop := containsAny("runaway-loop", "infinite loop", "recursive call", "unending loop")
	// Or programmatic detection of duplicate actions in plan steps
	duplicateCount := 0
	seenSteps := make(map[string]bool)
	for _, step := range packet.Plan {
		if seenSteps[step] {
			duplicateCount++
		}
		seenSteps[step] = true
	}
	if duplicateCount > 3 || hasRunawayLoop {
		triggers = append(triggers, "anomaly_detected")
	}

	// 4. Reward hacking detection (attempts to tamper with logs, bypass testing env constraints, or cheat the rewards)
	hasRewardHacking := containsAny("reward hacking", "exploit", "falsify", "tamper logs", "bypass sandbox", "cheat score")
	if hasRewardHacking {
		triggers = append(triggers, "reward_hacking")
	}

	// Final evaluation
	if len(triggers) > 0 {
		return KillSwitchOutput{
			Status:   "rejected",
			Reason:   "Kill-Switch hard stop triggered due to critical invariant violations.",
			Trigger:  triggers,
			Rollback: true,
		}
	}

	return KillSwitchOutput{
		Status:   "approved",
		Reason:   "All strict safety invariants and resource limits are satisfied.",
		Trigger:  []string{},
		Rollback: false,
	}
}

// =========================================================================
// ALIGNMENT SCORE & DIAGNOSTIC REASONER
// =========================================================================

// AlignmentResult holds the numerical and diagnostic evaluation of META-CORE constraints alignment.
type AlignmentResult struct {
	AlignmentScore    float64 // Numerical metric from 0.0 to 1.0
	DiagnosticVerdict string  // "balanced", "smart but dangerous", "safe but useless", "unstable architecture"
}

// CalculateAlignmentScore computes $A = f(R, E, K)$ and returns the alignment metrics and diagnostic state.
func CalculateAlignmentScore(packet DecisionPacket, empathy EmpathyOutput, killSwitch KillSwitchOutput) AlignmentResult {
	// R Logical Validity metric: bounded by plan confidence score
	rValidity := packet.Confidence
	if rValidity < 0 {
		rValidity = 0
	} else if rValidity > 1 {
		rValidity = 1
	}

	// E Human Safety metric: inversely proportional to vulnerability score if pass/modify, or 0 if blocked
	eSafety := 1.0 - empathy.VulnerabilityScore
	if empathy.Status == "block" {
		eSafety = 0.0
	}
	if eSafety < 0 {
		eSafety = 0
	}

	// K System Safety metric: 1.0 if approved, 0.0 if rejected
	kSafety := 1.0
	if killSwitch.Status == "rejected" {
		kSafety = 0.0
	}

	// Compute Alignment Score as normalized harmonic mean to penalize extreme imbalances, or fallback to arithmetic product.
	var score float64
	if rValidity == 0 || eSafety == 0 || kSafety == 0 {
		score = 0.0
	} else {
		// Harmonic mean: 3 / (1/R + 1/E + 1/K)
		score = 3.0 / ((1.0 / rValidity) + (1.0 / eSafety) + (1.0 / kSafety))
	}

	// Diagnostic Mode logic
	var verdict string
	if killSwitch.Status == "rejected" || len(killSwitch.Trigger) > 0 {
		verdict = "unstable architecture"
	} else if rValidity > 0.7 && eSafety < 0.4 {
		verdict = "smart but dangerous"
	} else if eSafety > 0.7 && rValidity < 0.4 {
		verdict = "safe but useless"
	} else {
		verdict = "balanced"
	}

	return AlignmentResult{
		AlignmentScore:    score,
		DiagnosticVerdict: verdict,
	}
}

// =========================================================================
// CONFLICT RESOLUTION & DEGRADATION MODES
// =========================================================================

// ConflictScenario represents the resolved decision flow of the constraint system.
type ConflictScenario string

const (
	ScenarioCorrectionWithConsent ConflictScenario = "correction_with_consent" // Scenario 1: modified/softened plan, K allows
	ScenarioSystemicBlocking     ConflictScenario = "systemic_blocking"       // Scenario 2: R/E passed, K blocks
	ScenarioHumanitarianVeto     ConflictScenario = "humanitarian_veto"       // Scenario 3: E blocks immediately, K not reached
	ScenarioStandardPass         ConflictScenario = "standard_pass"           // Default: passed all checks cleanly
)

// ResolveConflict coordinates the pipeline of R, E, and K layers to output the definitive action flow.
func ResolveConflict(packet DecisionPacket, userVulnerability float64, currentResources uint64, resourceLimit uint64) (ConflictScenario, EmpathyOutput, KillSwitchOutput) {
	// Step 1: E-Layer Auditing
	empathy := ValidateEmpathy(packet, userVulnerability)
	if empathy.Status == "block" {
		// Scenario 3: Humanitarian Veto. Stop execution immediately; Kill-Switch is bypassed to save resources.
		return ScenarioHumanitarianVeto, empathy, KillSwitchOutput{
			Status:   "rejected",
			Reason:   "Vetoed upstream by Empathy Layer",
			Trigger:  []string{"ethical_violation"},
			Rollback: true,
		}
	}

	// Step 2: K-Layer Auditing
	killSwitch := ValidateKillSwitch(packet, empathy, currentResources, resourceLimit)
	if killSwitch.Status == "rejected" {
		// Scenario 2: Systemic blocking of a coordinated plan (even if empathy allowed or suggested modify).
		return ScenarioSystemicBlocking, empathy, killSwitch
	}

	if empathy.Status == "modify" {
		// Scenario 1: Correction with consent of system. Empathy suggested modification, Kill-Switch approved.
		return ScenarioCorrectionWithConsent, empathy, killSwitch
	}

	// Clean Pass
	return ScenarioStandardPass, empathy, killSwitch
}

// DetermineDegradationMode analyzes validation outcomes and metrics to transit into protective operational states.
func DetermineDegradationMode(consecutiveKBlocks int, userVulnerability float64, rConfidence float64) string {
	if consecutiveKBlocks > 3 {
		// "Safe Mode": full ban on dynamic tools, limited decision depth.
		return "Safe Mode"
	}
	if userVulnerability > 0.7 {
		// "Empathy Override": stochastic Reasoning Engine R bypassed; deterministic templates used instead.
		return "Empathy Override"
	}
	if rConfidence < 0.4 {
		// "Conservative Planning": shorter planning horizons, step-by-step human operator confirmation.
		return "Conservative Planning"
	}
	return "Normal"
}

// =========================================================================
// META-CORE VALIDATOR SERVICE IMPLEMENTATION
// =========================================================================

// MetaCoreValidatorServer defines the service contract as specified in rek_service.proto.
type MetaCoreValidatorServer interface {
	ValidateAction(context.Context, *ActionEvaluationRequest) (*ActionEvaluationResponse, error)
	AuditReasoningStream(ctx context.Context, heartbeats <-chan *ReasoningStateHeartbeat, directives chan<- *SecurityDirective) error
}

// ValidatorService implements the MetaCoreValidatorServer interface.
type ValidatorService struct {
	ResourceLimit uint64
}

// NewValidatorService initializes a new validator service.
func NewValidatorService(limit uint64) *ValidatorService {
	if limit == 0 {
		limit = 100 // default resource threshold limit
	}
	return &ValidatorService{ResourceLimit: limit}
}

// ValidateAction validates a single action execution packet against empathy and system-safety invariants.
func (s *ValidatorService) ValidateAction(ctx context.Context, req *ActionEvaluationRequest) (*ActionEvaluationResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("request payload cannot be nil")
	}

	// Translate ActionEvaluationRequest -> DecisionPacket
	packet := DecisionPacket{
		Goal:            req.Goal,
		Plan:            req.PlanSteps,
		ExpectedOutcome: req.ExpectedOutcome,
		RiskProfile: RiskProfile{
			Ethical:     req.RiskProfile.Ethical,
			Legal:       req.RiskProfile.Legal,
			Operational: req.RiskProfile.Operational,
			HumanImpact: req.RiskProfile.HumanImpact,
		},
		ResourceCost: ResourceCost{
			Compute: fmt.Sprintf("%v millicores", req.ResourceCost.ComputeMillicores),
			Budget:  fmt.Sprintf("%v USD", req.ResourceCost.BudgetUSD),
			Time:    fmt.Sprintf("%v ms", req.ResourceCost.TimeoutMS),
		},
		Confidence: float64(req.Confidence),
	}

	// Default user vulnerability from request parameters or meta-context, here mapped or checked.
	var userVulnerability float64 = 0.0
	if strings.Contains(strings.ToLower(req.Goal), "stress") || strings.Contains(strings.ToLower(req.Goal), "overload") {
		userVulnerability = 0.8
	}

	// Resolve constraints pipeline
	scenario, empathy, killSwitch := ResolveConflict(packet, userVulnerability, req.ResourceCost.ComputeMillicores, s.ResourceLimit)

	// Determine final allocation decision enum mapping
	var decision AllocationDecision
	switch scenario {
	case ScenarioStandardPass:
		decision = AllocationDecisionApproved
	case ScenarioCorrectionWithConsent:
		decision = AllocationDecisionModified
	case ScenarioSystemicBlocking:
		decision = AllocationDecisionRejected
	case ScenarioHumanitarianVeto:
		decision = AllocationDecisionEmergencyStop
	default:
		decision = AllocationDecisionUnspecified
	}

	return &ActionEvaluationResponse{
		Decision: decision,
		EmpathyLayerOutput: EmpathyDetails{
			Status:                empathy.Status,
			VulnerabilityScore:    float32(empathy.VulnerabilityScore),
			ToneModification:      empathy.Modifications.Tone,
			IntensityModification: empathy.Modifications.Intensity,
			DelayMS:               1000,
			Reason:                empathy.Reason,
		},
		KillSwitchOutput: KillSwitchDetails{
			Status:            killSwitch.Status,
			ActivatedTriggers: killSwitch.Trigger,
			RollbackRequired:  killSwitch.Rollback,
			Reason:            killSwitch.Reason,
		},
	}, nil
}

// AuditReasoningStream continuously monitors streaming CoT reasoning traces to detect security anomalies or drift.
func (s *ValidatorService) AuditReasoningStream(ctx context.Context, heartbeats <-chan *ReasoningStateHeartbeat, directives chan<- *SecurityDirective) error {
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case hb, ok := <-heartbeats:
			if !ok {
				return nil
			}

			directive := &SecurityDirective{}
			traceLower := strings.ToLower(hb.LogicTrace)

			// Look for runaway execution or memory bounds
			if hb.CurrentMemoryBytes > s.ResourceLimit*1024*1024 {
				directive.AbortExecution = true
				directive.ForceRollback = true
				directive.ModificationInstruction = "Memory usage critical limit exceeded. Forcing hard reset."
			} else if strings.Contains(traceLower, "abuse") || strings.Contains(traceLower, "hack") {
				directive.AbortExecution = true
				directive.ForceRollback = true
				directive.ModificationInstruction = "CoT security drift detected: Ethics breach trigger."
			} else if strings.Contains(traceLower, "fatigue") || strings.Contains(traceLower, "tired") {
				directive.ModificationInstruction = "Transitioning communications to simplified supportive tone."
			}

			select {
			case <-ctx.Done():
				return ctx.Err()
			case directives <- directive:
			}
		}
	}
}
