// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package metacore

// DecisionPacket represents the data generated by the Reasoning Engine (R).
type DecisionPacket struct {
	Goal            string       `json:"goal"`
	Plan            []string     `json:"plan"`
	ExpectedOutcome string       `json:"expected_outcome"`
	RiskProfile     RiskProfile  `json:"risk_profile"`
	ResourceCost    ResourceCost `json:"resource_cost"`
	Confidence      float64      `json:"confidence"`
}

// RiskProfile outlines risks in various vectors.
type RiskProfile struct {
	Ethical     string `json:"ethical"`
	Legal       string `json:"legal"`
	Operational string `json:"operational"`
	HumanImpact string `json:"human_impact"`
}

// ResourceCost maps computational, monetary, and timing expectations.
type ResourceCost struct {
	Compute string `json:"compute"` // e.g. "millicores"
	Budget  string `json:"budget"`  // USD limits
	Time    string `json:"time"`    // max execution time
}

// EmpathyOutput represents semantic and emotional checks from the Empathy Layer (E).
type EmpathyOutput struct {
	Status             string        `json:"status"` // "pass", "modify", "block"
	Modifications      Modifications `json:"modifications"`
	VulnerabilityScore float64       `json:"vulnerability_score"` // scale of 0.0 to 1.0
	Reason             string        `json:"reason"`
}

// Modifications specify adjustments to communication/execution variables.
type Modifications struct {
	Tone      string `json:"tone"`
	Intensity string `json:"intensity"`
	Timing    string `json:"timing"`
	Channel   string `json:"channel"`
}

// KillSwitchOutput represents system-level approvals and triggers from the Kill-Switch Layer (K).
type KillSwitchOutput struct {
	Status   string   `json:"status"` // "approved", "rejected", "emergency_stop"
	Reason   string   `json:"reason"`
	Trigger  []string `json:"trigger"` // resource_limit, ethical_violation, anomaly_detected, reward_hacking
	Rollback bool     `json:"rollback"`
}
